version: "3.9"

services:
  backend:
    build:
      context: ./Server
    environment:
      - PORT=3001
      - CORS_ORIGIN=https://contentmanager.albertohugonin.it
    expose:
      - "3001"
    volumes:
      - cmsdata:/app/cmsmall.sqlite
      - sitename:/app/sitename.txt
      - public:/app/public
    restart: unless-stopped
    networks:
      - proxy

  frontend:
    build:
      context: ./Client/my-app
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  cmsdata:
  sitename:
  public: